version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: pip
    directory: /packages/image-generation
    schedule:
      interval: monthly
  - package-ecosystem: pip
    directory: /packages/image-to-3d
    schedule:
      interval: monthly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
